zuul:
  routes:
    abc:
      path: /abc/**
      serviceId: mircoservice-dept
  ignored-patterns:
    - /**/zuulTest
  sensitive-headers:

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: mq-consumer
  rabbitmq:
    host: 192.168.1.118
    port: 5672
    username: guest
    password: guest
